CREATE TABLE IF NOT EXISTS salesshipment (
                ID INTEGER NOT NULL,
                EntryID INTEGER NOT NULL,
                Status TEXT,
                OutboundDate DATE,
                OutboundNumber TEXT,
                Customer TEXT,
                ProductCode TEXT,
                ProductName TEXT,
                ProdCode TEXT,
                ProdName TEXT,
                Spec TEXT,
                CustProdName TEXT,
                BatchNumber TEXT,
                Unit TEXT,
                OutboundQty REAL,
                CostUnitPrice REAL,
                SalesUnitPrice REAL,
                CostAmount REAL,
                AmountExTax REAL,
                AmountIncTax REAL,
                GrossProfit REAL,
                GrossProfitMargin REAL,
                InvoiceQty REAL,
                InvoiceAmount REAL,
                ReceivableDate DATE,
                OrderCount INTEGER,
                CP TEXT,
                BP TEXT,
                TP TEXT,
                Salesperson TEXT,
                Developer TEXT,
                OrderNumber TEXT,
                Department TEXT,
                Company TEXT
            );